### ISSUE TITLE
The passed save_path is not a valid checkpoin

### ISSUE THREAD

**Issue by Espoirzxl** [hellonlp/classifier_multi_label_textcnn#6]
Traceback (most recent call last):
  File "predict.py", line 43, in <module>
    MODEL = ModelAlbertTextCNN()
  File "predict.py", line 26, in __init__
    self.albert, self.sess = self.load_model()
  File "predict.py", line 39, in load_model
    saver.restore(sess, ckpt.model_checkpoint_path)
ValueError: The passed save_path is not a valid checkpoint

**Comment by dcdethan** [comment]
棒！
